name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt --target ./src/scrape

      - name: Zip code
        run: |
          cd src/scrape
          zip -r ../scrape-books.zip .

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete --exclude '*.git*'
        env:
          AWS_S3_BUCKET: stanleys-bucket
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Update Lambda function
        uses: aws-actions/aws-cli@v1
        with:
          args: >
            lambda update-function-code --function-name scrape-books --s3-bucket stanleys-bucket --s3-key scrape-books.zip --region us-east-1
