name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update && sudo apt-get install -y awscli

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r src/scrape/requirements.txt --target src/scrape

      - name: Zip code
        run: |
          cd src/scrape
          zip -r ../../scrape-books.zip ./
          cd ../..

      - name: Deploy
        run: |
          aws lambda update-function-code \
            --function-name scrape-books \
            --zip-file fileb://scrape-books.zip \
            --region us-east-2 \
            --timeout 15 \
            --role arn:aws:iam::184082431850:role/my-s3-function-role \
            --handler main.lambda_handler \
            --profile default
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
