name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r src/scrape/requirements.txt --target src/scrape

      - name: Zip code
        run: |
          cd src/scrape
          zip -r ../../scrape-books.zip ./
          cd ../..

      - name: Deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-2
          function_name: scrape-books
          zip_file: scrape-books.zip
          handler: main.lambda_handler
          role: arn:aws:iam::184082431850:role/my-s3-function-role
          timeout: 15
